--1. LAST_NAME 이 Zlotkey 와 동일한 부서에 근무하는 모든 사원들의 사번 및 고용날짜를 조회한다.(결과값에서 Zlotkey 는 제외한다.)
SELECT EMPLOYEE_ID, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES
WHERE LAST_NAME = 'Zlotkey') AND LAST_NAME != 'Zlotkey'; -- " != " 연산자 이용 복습

--2. -- 사원이 존재하지 않는 국가를 조회하라.
SELECT DISTINCT COUNTRY_NAME FROM COUNTRIES C
LEFT JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
LEFT JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE EMPLOYEE_ID IS NULL;

--3. --자신의 상사가 자신 보다 늦게 입사한 사원의 모든 정보를 조회하라.
SELECT * FROM EMPLOYEES A
JOIN EMPLOYEES B ON A.MANAGER_ID = B.EMPLOYEE_ID
WHERE A.HIRE_DATE < B.HIRE_DATE;

--4. --사원수가 가장 많은 도시의 이름을 조회하라.
SELECT ROWNUM, MAX.* 
FROM
(SELECT L.CITY, COUNT(*) FROM LOCATIONS L
JOIN DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY L.CITY
ORDER BY COUNT(*) DESC
) MAX 
WHERE ROWNUM =1; --ROWNUM 사용법 복습
--DEPARTMENTS 테이블과 EMPLOYEES 테이블이 JOIN된 테이블을 CITY컬럼기준으로 그룹화, CITY컬럼과 컬럼에 걸린 개체의 카운트를 나타냄. 역순정렬.
--그렇게 걸러진 테이블에 ROWNUM으로 행간 숫자를 부여하고 그중 1번(최다사원)을 뽑아냄

--5. --담당 직무의 최대 연봉을 받고 있는 사원들의 모든 정보를 조회하라.
SELECT * FROM EMPLOYEES E
JOIN
(
SELECT DEPARTMENT_ID, MAX(SALARY) AS MAXSAL FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
) MAX
ON E.DEPARTMENT_ID = MAX.DEPARTMENT_ID
WHERE E.SALARY = MAX.MAXSAL; 
--WHERE절에서 집계함수 대신 별칭쓸것, 서브쿼리만들어서 EMP테이블과 JOIN활용법 다시 보기


--6. 사원수가 가장 많은 도시에서 근무하는 모든 사원들의 연봉 총합을 조회하라.
--SELECT SUM(SALARY) FROM
--SELECT SUM(SALARY) FROM
--(
--SELECT L.CITY, COUNT(*) AS CNT FROM EMPLOYEES E
--JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
--JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
--GROUP BY L.CITY
--) MAX
--;






