CREATE TABLE EMP_TRIG
AS SELECT * FROM EMP;

INSERT INTO EMP_TRIG(EMPNO) VALUES(7777);
UPDATE EMP_TRIG SET ENAME='MIKE' WHERE EMPNO=7703;
DELETE FROM EMP_TRIG WHERE EMPNO=7777;

CREATE TABLE EMP_LOG(
        TABLENAME VARCHAR2(10),
        DML_TYPE VARCHAR2(10),
        EMPNO NUMBER(4),
        USER_NAME VARCHAR2(30),
        CHANGE_DATE DATE
);

DELETE FROM EMP_TRIG WHERE DEPTNO=10;
INSERT INTO EMP_TRIG(DEPTNO) VALUES(10);
DELETE FORM EMP_TRIG WHERE DEPTNO=10;