/*
TCL(DCL)
*/
DROP TABLE SAL_TCL;
CREATE TABLE SAL_TCL
AS SELECT * FROM SALGRADE;
SELECT * FROM SAL_TCL;

INSERT INTO SAL_TCL(GRADE, LOSAL, HISAL)
VALUES(6,5000,7000);
UPDATE SAL_TCL SET LOSAL=3001, HISAL=4999
WHERE GRADE=5;
DELETE FROM SAL_TCL WHERE GRADE=3;
COMMIT;
